# Targets

all:	mr-pr-mpi

mr-pr-mpi:	mr-pr-mpi.o $(USRLIB)
	$(LINK) $(LINKFLAGS) mr-pr-mpi.o $(USRLIB) $(SYSLIB) -o mr-pr-mpi


clean:
	rm *.o mr-pr-mpi

# Rules

%.o:%.cpp
	$(CPP) $(CCFLAGS) -c $<

%.o:%.c
	$(CC) $(CCFLAGS) -c $<
